language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - "node_modules"
install:
  - npm install

jobs:
  include:
    - stage: build docker image
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t time-manager-web-interface-v2 .
        - docker images
        - docker tag time-manager-web-interface-v2 $DOCKER_USERNAME/time-manager-web-interface-v2
        - docker push $DOCKER_USERNAME/time-manager-web-interface-v2